name: Studies project CI/CD integrated with azdo

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Run Checkout step
                uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Set up nodejs
                uses: actions/setup-node@v4
                with:
                    node-version: 20

            -   name: Setup WebDriver
                uses: webdriverio/github-action@v1
                with:
                    node-version: 20

            -   name: Start Selenium Server
                uses: selenium-standalone-server/github-action@v1

            -   name: Install dependencies
                working-directory: mwo-frontend
                run: npm ci

            -   name: Start Angular app
                working-directory: mwo-frontend
                run: npm start

            -   name: Build backend with Gradle
                working-directory: mwo-backend
                run: ./gradlew build
                env:
                    - POSTGRES_USER=postgres
                    - BROWSER=chrome
                    - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5000/cinema
                    - POSTGRES_PASSWORD=postgres

#            -   name: Build Angular app and run Selenium tests
#                working-directory: mwo-frontend
#                env:
#                    - POSTGRES_USER=postgres
#                    - BROWSER=chrome
#                    - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5000/cinema
#                    - POSTGRES_PASSWORD=postgres
#                run: npm run test-selenium

#            -   name: Creating bug AZDO tasks with failed selenium tests
#                uses: stefanstranger/azuredevops-bug-action@1.1
#                if: failure()
#                with:
#                    OrganizationName: "final-project-mwo"
#                    PAT: "PAT"
#                    ProjectName: "mwo-project"
#                    AreaPath: "mwo-project\\Automation"
#                    IterationPath: "mwo-project"
#                    GithubToken: "GithubToken"
#                    WorkflowFileName: "main.yml"
#                env:
#                    PAT: ${{secrets.PAT}}
#                    GithubToken: ${{secrets.GITHUBRESTAPISECRET}}
